name: Routine
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/login_graphic.svg
    - assets/images/google.svg
    - assets/images/facebook.svg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
      #   # - asset: assets/fonts/Comfortaa-Light.ttf
      #   # - asset: assets/fonts/Comfortaa-Medium.ttf
      #   # - asset: assets/fonts/Comfortaa-SemiBold.ttf